// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaherdxwzftzgazplwzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphaGVyZHh3emZ0emdhenBsd3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjA4MTEsImV4cCI6MjA2NTgzNjgxMX0.BFlaz60sLyhZV9DwttuJWJ9uCvWFPE4ZIhEUyhAxsiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});